<a href="https://colab.research.google.com/github/VarshuGangasagre/VarshuGangasagre/blob/main/Bioinformatics_TSk1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Open Fasta File
def count_sequences(fasta_file):
    sequence_count = 0

    with open(fasta_file, 'r') as file:
        for line in file:
            line = line.strip()
            if line.startswith('>'):
                sequence_count += 1

    return sequence_count

# Provide the path to your FASTA file
fasta_file_path = '/sequenceprotein.fasta'

# Call the function to count sequences
num_sequences = count_sequences(fasta_file_path)

# Print the number of sequences
print("Number of sequences:", num_sequences)


Number of sequences: 1


In [ ]:
# Function to calculate GC content
def calculate_gc_content(sequence):
    gc_count = 0
    total_count = 0

    # Iterate over each nucleotide in the sequence
    for nucleotide in sequence:
        if nucleotide == 'G' or nucleotide == 'C':
            gc_count += 1
        total_count += 1

    # Calculate GC content percentage
    gc_content = (gc_count / total_count) * 100
    return gc_content

# Main code
dna_sequence = "ATCGATCGATCGATCGATTCGCGATTCTGCATGCATATGCGCGCGCGCGC"
gc_content = calculate_gc_content(dna_sequence)
print("GC content:", gc_content)


GC content: 57.99999999999999


In [ ]:
#To translate a DNA sequence into its corresponding protein sequence
!pip install biopython

from Bio.Seq import Seq

def translate_dna_to_protein(dna_sequence):
    # Create a Seq object from the DNA sequence
    dna_seq = Seq(dna_sequence)

    # Translate the DNA sequence to protein
    protein_seq = dna_seq.translate()

    return protein_seq

# DNA sequence to be translated
dna_sequence = "ATGGTCTCGATTGAGGACGAGGACGAGGACGAGGACGAGGACTAG"

# Translate DNA to protein
protein_sequence = translate_dna_to_protein(dna_sequence)

# Print the protein sequence
print("Protein sequence:", protein_sequence)


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Protein sequence: MVSIEDEDEDEDED*


In [ ]:
#To extract the coding sequence (CDS) from a GenBank file using Biopython
from Bio import SeqIO

def extract_coding_sequences(genbank_file):
    coding_sequences = []

    for record in SeqIO.parse(genbank_file, "genbank"):
        for feature in record.features:
            if feature.type == "CDS":
                cds_sequence = feature.extract(record.seq)
                coding_sequences.append(cds_sequence)

    return coding_sequences

# GenBank file path
genbank_file_path = '/path/to/your/genbank/file.gb'

# Extract coding sequences
coding_sequences = extract_coding_sequences(genbank_file_path)

# Print the extracted coding sequences
for i, cds_sequence in enumerate(coding_sequences):
    print(f"Coding Sequence {i+1}: {cds_sequence}")


In [ ]:
#To search for a specific motif or pattern in a DNA sequence using regular expressions
import re

def search_motif_in_dna(dna_sequence, motif):
    matches = re.findall(motif, dna_sequence)
    return matches

# DNA sequence
dna_sequence = "ATGCGATAGCTAGCTACGATGCGAT"

# Motif to search for
motif = "ATG"

# Search for the motif in the DNA sequence
matches = search_motif_in_dna(dna_sequence, motif)

# Print the matches
print("Matches found:", matches)


Matches found: ['ATG', 'ATG']


In [ ]:
#MSA using CLUSTAL
!apt-get install -y clustalw

from Bio import AlignIO

alignment_file_path = '/clustalw.aln'
alignment = AlignIO.read(alignment_file_path, 'clustal')
print(alignment)


Reading package lists... Done
Building dependency tree       
Reading state information... Done
clustalw is already the newest version (2.1+lgpl-6build1).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
Alignment with 3 rows and 48432 columns
CATTGGATTGATCAAATCTTGTTCTTCGTAATAGCGAATCTGTC...AAA sequence1
--------------------------------------------...--- sequence2
--------------------------------------------...--- sequence3


In [ ]:
from Bio.SeqUtils.ProtParam import ProteinAnalysis

def calculate_molecular_weight(protein_sequence):
    protein_analyzer = ProteinAnalysis(protein_sequence)
    molecular_weight = protein_analyzer.molecular_weight()
    return molecular_weight

# Protein sequence
protein_sequence = "MKWVTFISLLFLFSSAYSRGVFRRDAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPGACTHSGCPUHCGTF"

# Calculate molecular weight
molecular_weight = calculate_molecular_weight(protein_sequence)

# Print the molecular weight
print("Molecular weight:", molecular_weight)


Molecular weight: 8421.513799999997


In [ ]:
#To generate a random DNA sequence of a given length
import random

def generate_random_dna_sequence(length):
    bases = ['A', 'C', 'G', 'T']
    random_sequence = ''.join(random.choices(bases, k=length))
    return random_sequence

# Specify the desired length of the random DNA sequence
sequence_length = 150

# Generate a random DNA sequence
random_sequence = generate_random_dna_sequence(sequence_length)

# Print the random DNA sequence
print("Random DNA sequence:", random_sequence)


Random DNA sequence: TTTGTACTAACTGCGTACAGTACAGTACTGCTCTCGGCGGGTCGTACGTCGTTGGGTTGTCCATCAGCTCAAGGAGAATCAACCTTTAGTTGGCTGGCTTTAGAAGCTTGCCCTAAGAGAACAAGCTATAATAGTGATGGAGAAATTGTG


In [ ]:
#To retrieve protein information from UniProt using an accession number
import requests

def retrieve_protein_info(accession_number):
    url = f"https://www.uniprot.org/uniprot/{accession_number}.txt"
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        protein_info = response.text
        return protein_info
    else:
        print(f"Failed to retrieve protein information for accession number: {accession_number}")
        return None

# Accession number of the protein
accession_number = "P12348"

# Retrieve protein information
protein_info = retrieve_protein_info(accession_number)

# Print the protein information
print("Protein information:")
print(protein_info)


Protein information:
ID   PER_DROPS               Reviewed;        1271 AA.
AC   P12348; Q29I05;
DT   01-OCT-1989, integrated into UniProtKB/Swiss-Prot.
DT   16-DEC-2008, sequence version 3.
DT   03-MAY-2023, entry version 134.
DE   RecName: Full=Period circadian protein;
GN   Name=per; ORFNames=GA15408;
OS   Drosophila pseudoobscura pseudoobscura (Fruit fly).
OC   Eukaryota; Metazoa; Ecdysozoa; Arthropoda; Hexapoda; Insecta; Pterygota;
OC   Neoptera; Endopterygota; Diptera; Brachycera; Muscomorpha; Ephydroidea;
OC   Drosophilidae; Drosophila; Sophophora.
OX   NCBI_TaxID=46245;
RN   [1]
RP   NUCLEOTIDE SEQUENCE [GENOMIC DNA].
RC   STRAIN=Ayala;
RX   PubMed=3208754; DOI=10.1002/j.1460-2075.1988.tb03279.x;
RA   Colot H.V., Hall J.C., Rosbash M.;
RT   "Interspecific comparison of the period gene of Drosophila reveals large
RT   blocks of non-conserved coding DNA.";
RL   EMBO J. 7:3929-3937(1988).
RN   [2]
RP   NUCLEOTIDE SEQUENCE [LARGE SCALE GENOMIC DNA].
RC   STRAIN=MV2-25 / Tucson 1401

In [ ]:
#To perform a BLAST search against a local or online database
from Bio.Blast import NCBIWWW, NCBIXML

def perform_blast_search(sequence, database="nr", program="blastn"):
    result_handle = NCBIWWW.qblast(program, database, sequence)
    blast_records = NCBIXML.parse(result_handle)
    return blast_records

# DNA or protein sequence
sequence = "ATGCGATAGCTAGCTACGATGCGAT"

# Perform BLAST search
blast_records = perform_blast_search(sequence)

# Process the blast records
for blast_record in blast_records:
    for alignment in blast_record.alignments:
        for hsp in alignment.hsps:
            # Access the relevant information
            print("Alignment:")
            print("Sequence:", alignment.title)
            print("E-value:", hsp.expect)
            print("Alignment length:", hsp.align_length)
            print("Alignment:", hsp.query)
            print("        ", hsp.match)
            print("        ", hsp.sbjct)
            print()


Alignment:
Sequence: gi|2191754237|emb|OV815308.1| Gymnoscelis rufifasciata genome assembly, chromosome: 7
E-value: 5.64851
Alignment length: 24
Alignment: ATGCGATAGCTAGCTACGATGCGA
         ||||| ||||||||||||||||||
         ATGCGGTAGCTAGCTACGATGCGA



In [ ]:
#To calculate the isoelectric point (pI) of a protein sequence
from Bio.SeqUtils.IsoelectricPoint import IsoelectricPoint

def calculate_pI(protein_sequence):
    pI_calculator = IsoelectricPoint(protein_sequence)
    pI = pI_calculator.pi()
    return pI

# Protein sequence
protein_sequence = "MKWVTFISLLFLFSSAYSRGVFRRDAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFGHYTSDFGHYTHGYTDGSHSGSHJAAJAHSGS"

# Calculate isoelectric point
pI = calculate_pI(protein_sequence)

# Print the isoelectric point
print("Isoelectric point (pI):", pI)


Isoelectric point (pI): 7.983522987365723


In [ ]:
#To perform Principal Component Analysis (PCA) on gene expression data
import numpy as np
from sklearn.decomposition import PCA

# Gene expression data (example)
gene_expression_data = np.array([[1.2, 3.5, 2.1, 4.0],
                                [0.8, 2.9, 1.5, 3.2],
                                [2.1, 4.3, 3.2, 5.1],
                                [1.5, 3.2, 2.9, 4.3]])

# Create a PCA object with desired number of components
pca = PCA(n_components=2)

# Perform PCA on the gene expression data
pca_result = pca.fit_transform(gene_expression_data)

# Print the explained variance ratio
print("Explained variance ratio:")
print(pca.explained_variance_ratio_)

# Print the transformed data (PCA scores)
print("Transformed data (PCA scores):")
print(pca_result)


Explained variance ratio:
[0.93620736 0.06207559]
Transformed data (PCA scores):
[[-0.34288542 -0.21309016]
 [-1.5619741  -0.07996645]
 [ 1.62123017 -0.21014527]
 [ 0.28362935  0.50320188]]


In [ ]:
#To calculate the reverse complement of a DNA sequence
from Bio.Seq import Seq

def calculate_reverse_complement(dna_sequence):
    # Create a Seq object from the DNA sequence
    seq = Seq(dna_sequence)

    # Calculate the reverse complement
    reverse_complement = seq.reverse_complement()

    return str(reverse_complement)

# Example DNA sequence
dna_sequence = "ATCGGCGTAA"

# Calculate the reverse complement
reverse_complement = calculate_reverse_complement(dna_sequence)

print("Original sequence:", dna_sequence)
print("Reverse complement:", reverse_complement)


Original sequence: ATCGGCGTAA
Reverse complement: TTACGCCGAT


In [ ]:
#To calculate the distance matrix using DNA sequences
# Install Biopython library
!pip install biopython

# Import necessary libraries
from Bio import pairwise2
from Bio import SeqIO
import numpy as np

# Define a list of DNA sequences
sequences = [
    "ATGCTAGCTAGCTA",
    "ATGCATCGATCGAT",
    "ATGCTAGCTAGCTA",
    "ATGCGCGCGCGCGC"
]

# Calculate distance matrix
num_sequences = len(sequences)
distance_matrix = np.zeros((num_sequences, num_sequences))

for i in range(num_sequences):
    for j in range(i+1, num_sequences):
        alignment = pairwise2.align.globalxx(sequences[i], sequences[j], one_alignment_only=True)
        distance = 1 - (alignment[0].score / max(len(sequences[i]), len(sequences[j])))
        distance_matrix[i, j] = distance
        distance_matrix[j, i] = distance

# Print distance matrix
print(distance_matrix)


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
[[0.         0.35714286 0.         0.42857143]
 [0.35714286 0.         0.35714286 0.42857143]
 [0.         0.35714286 0.         0.42857143]
 [0.42857143 0.42857143 0.42857143 0.        ]]


/usr/local/lib/python3.10/dist-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(


In [ ]:
# Install bioservices library
!pip install bioservices

# Import necessary libraries
from bioservices.kegg import KEGG

# Create a KEGG object
kegg = KEGG()

# Perform pathway enrichment analysis
def perform_pathway_enrichment(gene_list, organism):
    # Convert gene list to KEGG gene IDs
    kegg_genes = kegg.conv("genes", "uniprot:" + " ".join(gene_list))

    # Get KEGG pathway annotations
    pathways = kegg.get_pathway_by_genes(kegg_genes, organism)

    # Print enriched pathways
    for pathway in pathways:
        print("Pathway ID:", pathway)
        print("Pathway Name:", pathways[pathway])

# Define the gene list and organism
gene_list = ["gene1", "gene2", "gene3"]  # Replace with your gene list
organism = "hsa"  # Replace with the KEGG organism code for your organism of interest (e.g., "hsa" for human)

# Perform pathway enrichment analysis
perform_pathway_enrichment(gene_list, organism)


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.9/191.9 kB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.7/58.7 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.9/144.9 kB 14.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 63.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 10.8 MB/s eta 0:00:00
  Created wheel for bioservices: filename=bioservices-1.11.2-py3-none-any.whl size=223238 sha256=34c9780586a5b56256ebc723e6e87a3865b56449c63bbe52d033111885f3a46a
  Stored in directory: /root/.cache/pip/wheels/bf/ac/b3/dc05e53581bbb58641e9ac52428b89d7fc0d9ddc44f9b16456
  Created wheel for easydev: filename=easydev-0.12.1-py3-none-any.wh

ValueError: ignored

# New section

# New section