<a href="https://colab.research.google.com/github/VarshuGangasagre/VarshuGangasagre/blob/main/Copy_of_Data_Mining_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=['apple','banana','orange','lichi']
print(x)

['apple', 'banana', 'orange', 'lichi']


In [ ]:
x=['apple','banana','orange','lichi']
print('lichi'in x)

True


In [ ]:
a=5
b=0.6
c='Varsha'
print("type of the variable:",type(a));
print("type of the variable:",type(b));
print("type of the variable:",type(c));

type of the variable: <class 'int'>
type of the variable: <class 'float'>
type of the variable: <class 'str'>


In [ ]:
x.append('mango')

In [ ]:
print(x)

['apple', 'banana', 'orange', 'lichi', 'mango']


In [ ]:
y={"apple","cherry","mango"}
type(y)

set

In [ ]:
type(x)

list

In [ ]:
y.add("lichi")
print(y)

{'cherry', 'mango', 'lichi', 'apple'}


In [ ]:
z=('apple','orange','berry')
print(z)
type(z)

('apple', 'orange', 'berry')


tuple

In [ ]:
x1={"s","p","q","r"}
type(x1)

set

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [ ]:
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [ ]:
c=50
d=60
print("c")if c>d else print("D")

D


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range (1,11):
  print("i",i)

i 1
i 2
i 3
i 4
i 5
i 6
i 7
i 8
i 9
i 10


In [ ]:
for x in range(2,41,2):
  print(x)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40


In [ ]:
fruits=["apple","banana","cherry","lichi"]
for i in fruits:
  print(i)
  if i=="banana":
    break

apple
banana


In [ ]:
fruits=["apple","banana","cherry","lichi"]
for x in fruits:
  if x=="banana":
    break
    print(x)

In [ ]:
print(x)

banana


In [ ]:
#Nested Loop
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [ ]:
#While loop
i=1
while i<6:
  print(i)
  i=i+1
  print("incremented",i)

1
incremented 2
2
incremented 3
3
incremented 4
4
incremented 5
5
incremented 6


In [ ]:
import numpy as np
#let us understand why numpy
distance=[10,15,17,20,26]
time=[0.3,0.7,55,7.5,1.2]
type(distance)
type(time)

list

In [ ]:
# Introduction To Functions (Built in functions)
#abs() absoulate value of a number
#integer number
integer=-50
print('Absolute value of -50 is:',abs(integer))


Absolute value of -50 is: 50


In [ ]:
#all() It returns if all the items in passed iterable are true
a=[1,2,3,4,5]
print(all (a))
print()

True



In [ ]:
# bin() function is used to return the binary representation of the integer
x=10
y=bin(x)
print(y)

0b1010


In [ ]:
#bool() converts a value to boolean (true or false)using standard truth testing procedure
demo1=[0]
print(demo1,'is',bool(demo1))

[0] is True


In [ ]:
#bytes() It is used to returning a byte object
string="Hello"
array=bytes(string,'utf-8')
print(array)

b'Hello'


In [ ]:
#exec() functions is used to dyanamic exection of python program than can either be a string or object code
a=20
exec('print(a==10)')
exec('print(a+10)')
exec("print(a==20)")


False
30
True


In [ ]:
#sum()
num=[1,2,3,4,5,6,7]
demo=sum(num)
print(demo)

28


In [ ]:
#any() function returns true if any item in an iterable is true or false
L=[41,31,56,75]
print(any(L))

True


In [ ]:
#eval() functions parses the expression is passed to it and executes python expression
x=30
print(eval('x*10'))

300


In [ ]:
#float() 
x=10
print(type(x))
y=float (9)
print(type(y))
a="0.11"
print(type(a))
b=float("0.11")
print(type(b))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'float'>


In [ ]:
#formal() Two-decimal formal
data="The bag {price:2f}dollars!"
print(data.format(price=149))


The bag 149.000000dollars!


In [ ]:
# Iter()
list=[2,3,4,5,6]
list_iter=iter(list)
print(list)
len(list)
min(list)
max(list)

[2, 3, 4, 5, 6]


6

In [ ]:
#len()
len(list)

5

In [ ]:
#max()
max(list)

6

In [ ]:
#set()
list=[1,2,3,4,5,6]
a=set(list)
print(a)

{1, 2, 3, 4, 5, 6}


In [ ]:
#sorted()
ab=[9,1,2,4,5,6,6,9]
b=sorted(ab)
print(b)


[1, 2, 4, 5, 6, 6, 9, 9]


In [ ]:
#int()
val1=int(20)
val2=int(11.56)
val3=int(75)
print(val1,val2,val3)

20 11 75


In [ ]:
#pow() To the power
print(pow(2,3))

8


In [ ]:
#round()
print(round(20.5))

20


In [ ]:
# key argument
def new_function(name3,name2,name1,name4):
  print(name2)
  new_function(name1="V",name2="S",name3="P",name="A")
  print(name3)

In [ ]:
# default parameter value
def my_country(country="India"):
    print("My country name"+country)
my_country("America")
my_country("Japan")
my_country("England")
my_country()
my_country("Russia")

My country nameAmerica
My country nameJapan
My country nameEngland
My country nameIndia
My country nameRussia


In [ ]:
#passing a list to the function as an argument
def my_fruitlist(fruits):
  print(fruits)
  fruits=["apple","banana","cherry"]
  my_fruitlist(fruits)
  type(fruits)

In [ ]:
def func1(*args):
    print(type(args)) 
    print(args) 
    print(*args) 

func1(1,2,3,4,5,6,7,"goodbye")

<class 'tuple'>
(1, 2, 3, 4, 5, 6, 7, 'goodbye')
1 2 3 4 5 6 7 goodbye


In [ ]:
a=10
def sum():
  W=10
  return print(a+W)
  sum()
  print(a)

In [ ]:
#multiple argument
x=lambda x,y: x+y
print(x(50,6))


56


In [ ]:
#single dimensional array
single_array=np.array([2,3,4,5,6,7])
print("single dimensional array using numpy",single_array)

single dimensional array using numpy [2 3 4 5 6 7]


In [ ]:
#create multidimensional array
multi_dimensional=np.array([(3,4,5,6),(8,6,5,4),(5,6,7,8)])
print(multi_dimensional)
type(multi_dimensional)


[[3 4 5 6]
 [8 6 5 4]
 [5 6 7 8]]


numpy.ndarray

In [ ]:
multi_dimensional.ndim

2

In [ ]:
#check memory size of the array with numpy
print(single_array)
print("memory size of the array:",single_array.itemsize)

[2 3 4 5 6 7]
memory size of the array: 8


In [ ]:
print(multi_dimensional)
print("memory size of the array:",multi_dimensional.itemsize)

[[3 4 5 6]
 [8 6 5 4]
 [5 6 7 8]]
memory size of the array: 8


In [ ]:
#check the type of the array with numpy
print("type of the array:",single_array.dtype)
print("type of the array:",multi_dimensional.dtype)

type of the array: int64
type of the array: int64


In [ ]:
#check the size of the array with numpy
print("total elements present in the array:",single_array.size)
print("total elements present in the array:",multi_dimensional.size)

total elements present in the array: 6
total elements present in the array: 12


In [ ]:
#check the shape of the array with numpy
print("shape of the array:",single_array.shape)
print("shape of the array:",multi_dimensional.shape)

shape of the array: (6,)
shape of the array: (3, 4)


In [ ]:
#Reshape the array with numpy
multi_dimensional=np.array([(6,7,8),(10,11,12)])
print(multi_dimensional)
print(multi_dimensional.ndim)
print(multi_dimensional.shape)

[[ 6  7  8]
 [10 11 12]]
2
(2, 3)


In [ ]:
#concat two array
first_array=np.array([12,16,14])
second_array=np.array([45,67,87])
new_array=np.concatenate((first_array,second_array))
print(new_array)

[12 16 14 45 67 87]


In [ ]:
#sort array with numpy
print('sorted order:',np.sort(new_array))


sorted order: [12 14 16 45 67 87]


In [ ]:
arr1=np.array([100,67,89,54,32,23,2,1,8,10])
np.sort(arr1)

array([  1,   2,   8,  10,  23,  32,  54,  67,  89, 100])

In [ ]:
# Array indexing with Numpy
X=([90,12,34,14,15,16])
print(new_array)
print('first element start with 0 in array:',X[4])

[12 16 14 45 67 87]
first element start with 0 in array: 15


In [ ]:
#array slicing with numpy
print(X)
print('starts from 1 index to go till 4',new_array[0:5])

[90, 12, 34, 14, 15, 16]
starts from 1 index to go till 4 [12 16 14 45 67]


In [ ]:
#2d numpy arrays matrix
my_tuple=((1,2),(3,4),(5,6))
my_tup_arr=(np.array(my_tuple))
print(my_tup_arr)
print(type(my_tup_arr))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [ ]:
x is: [[0 2 4 6 7] 
      [3 4 6 7 8]]
y=x.copy()
print("y is :\n",y)
print("\nx is copied to y")

SyntaxError: ignored